# Install skailr-agents (.claude + .cursor trees + scripts/skills) into a target project.
# Usage: .\install.ps1 -TargetPath C:\path\to\project [-ClaudeOnly] [-CursorOnly]

param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$TargetPath,
    [switch]$ClaudeOnly,
    [switch]$CursorOnly
)

$ErrorActionPreference = "Stop"

if ($ClaudeOnly -and $CursorOnly) {
    Write-Error "Use only one of -ClaudeOnly or -CursorOnly"
}

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not (Test-Path $TargetPath)) {
    New-Item -ItemType Directory -Path $TargetPath -Force | Out-Null
}
$Target = (Resolve-Path $TargetPath).Path

$Mode = if ($ClaudeOnly) { "claude" } elseif ($CursorOnly) { "cursor" } else { "both" }
Write-Host "Installing skailr-agents → $Target (mode: $Mode)"

function Install-Scripts {
    New-Item -ItemType Directory -Path "$Target\scripts\skailr" -Force | Out-Null
    New-Item -ItemType Directory -Path "$Target\scripts\hooks" -Force | Out-Null
    Get-ChildItem "$ScriptDir\scripts\skailr\*.mjs" | ForEach-Object {
        Copy-Item $_.FullName "$Target\scripts\skailr\" -Force
        Write-Host "  + scripts/skailr/$($_.Name)"
    }
    $hook = Join-Path $ScriptDir "scripts\hooks\pre-commit.sample"
    if (Test-Path $hook) {
        Copy-Item $hook "$Target\scripts\hooks\" -Force
        Write-Host "  + scripts/hooks/pre-commit.sample"
    }
}

# CLAUDE.md has two independently-owned zones (full contract: skill
# maintain-claude-md) — a Skailr-owned intake block, kept in sync on every
# install/upgrade exactly as CLAUDE.md always has been, and a project-owned
# conventions block written later by /map-repo (never by this installer) that
# must survive an upgrade untouched. Same class of problem settings.skailr.json
# already solves for its own file — a blind overwrite here would silently
# destroy accumulated project knowledge on the next install.ps1 run.
function Install-ClaudeMd {
    $pack = Join-Path $ScriptDir "CLAUDE.md"
    $target = "$Target\CLAUDE.md"
    if (-not (Test-Path $pack)) { return }

    if (-not (Test-Path $target)) {
        Copy-Item $pack $target -Force
        Write-Host "  + CLAUDE.md"
        return
    }

    # Legacy wholly-generated file (pre-2.0.0, before the intake-zone markers):
    # no conventions zone + a generated first line means no project-owned
    # content by construction — replace wholesale instead of appending a
    # duplicate intake block. Keep in sync with install.sh's install_claude_md.
    $existingText = Get-Content $target -Raw
    if ($existingText -notmatch [regex]::Escape("<!-- skailr:conventions:start -->")) {
        $firstLine = ($existingText -split "`r?`n", 2)[0]
        if ($firstLine.StartsWith("<!-- Generated by scripts/remirror.sh") -or $firstLine.StartsWith("# Skailr intake")) {
            Copy-Item $pack $target -Force
            Write-Host "  = CLAUDE.md (legacy generated file replaced; no project content present)"
            return
        }
    }

    $startMarker = "<!-- skailr:intake:start -->"
    $endMarker = "<!-- skailr:intake:end -->"
    $blockPattern = [regex]::Escape($startMarker) + "(?s).*?" + [regex]::Escape($endMarker)

    $packText = Get-Content $pack -Raw
    $targetText = Get-Content $target -Raw
    $packBlockMatch = [regex]::Match($packText, $blockPattern)
    $targetBlockMatch = [regex]::Match($targetText, $blockPattern)

    if ($packBlockMatch.Success -and $targetBlockMatch.Success) {
        $newText = $targetText.Substring(0, $targetBlockMatch.Index) `
            + $packBlockMatch.Value `
            + $targetText.Substring($targetBlockMatch.Index + $targetBlockMatch.Length)
        Set-Content -Path $target -Value $newText -NoNewline
        Write-Host "  = CLAUDE.md (intake zone refreshed; project conventions preserved)"
    } else {
        # No (complete) Skailr zone yet — first install over a human's own CLAUDE.md,
        # or an upgrade from before this marker existed. Append rather than guess at
        # or destroy unknown existing content.
        $newText = $targetText.TrimEnd() + "`r`n`r`n" + $packText
        Set-Content -Path $target -Value $newText -NoNewline
        Write-Host "  = CLAUDE.md (intake block appended; existing content preserved)"
    }
}

function Install-Claude {
    $dirs = @(
        "$Target\.claude\agents",
        "$Target\.claude\commands",
        "$Target\.claude\skills",
        "$Target\.claude\tmp",
        "$Target\.claude\repo",
        "$Target\.claude\program\schemas"
    )
    foreach ($d in $dirs) {
        New-Item -ItemType Directory -Path $d -Force | Out-Null
    }

    $agentsRoot = Join-Path $ScriptDir ".claude\agents"
    Get-ChildItem $agentsRoot -Directory | ForEach-Object {
        $team = $_.Name
        $dest = Join-Path $Target ".claude\agents\$team"
        New-Item -ItemType Directory -Path $dest -Force | Out-Null
        Get-ChildItem $_.FullName -Filter "*.md" | ForEach-Object {
            Copy-Item $_.FullName $dest -Force
            Write-Host "  + .claude/agents/$team/$($_.Name)"
        }
    }
    Get-ChildItem "$ScriptDir\.claude\commands\*.md" | ForEach-Object {
        Copy-Item $_.FullName "$Target\.claude\commands\" -Force
        Write-Host "  + .claude/commands/$($_.Name)"
    }
    if (Test-Path "$ScriptDir\.claude\skills") {
        Copy-Item "$ScriptDir\.claude\skills\*" "$Target\.claude\skills\" -Recurse -Force
        Write-Host "  + .claude/skills/"
    }

    if (Test-Path "$ScriptDir\.claude\program\schemas") {
        Get-ChildItem "$ScriptDir\.claude\program\schemas\*" | ForEach-Object {
            Copy-Item $_.FullName "$Target\.claude\program\schemas\" -Force
            Write-Host "  + .claude/program/schemas/$($_.Name)"
        }
    }

    # Copy settings.skailr.json only if absent: it may carry a consumer's telemetry
    # enable/disable choice (optional `telemetry.enabled` key), which a blind overwrite
    # on upgrade would silently reset. Preserve consumer intent (AC-26).
    $settings = Join-Path $ScriptDir ".claude\settings.skailr.json"
    if (Test-Path $settings) {
        if (Test-Path "$Target\.claude\settings.skailr.json") {
            Write-Host "  = .claude/settings.skailr.json exists (preserved; consumer telemetry choice kept)"
        } else {
            Copy-Item $settings "$Target\.claude\settings.skailr.json" -Force
            Write-Host "  + .claude/settings.skailr.json"
        }
    }

    $intake = Join-Path $ScriptDir ".claude\intake.md"
    if (Test-Path $intake) {
        Copy-Item $intake "$Target\.claude\intake.md" -Force
        Write-Host "  + .claude/intake.md"
    }

    Install-ClaudeMd

    foreach ($keep in @("$Target\.claude\tmp\.gitkeep", "$Target\.claude\program\.gitkeep", "$Target\.claude\repo\.gitkeep")) {
        if (-not (Test-Path $keep)) { New-Item -ItemType File -Path $keep -Force | Out-Null }
    }
    Write-Host "  + .claude/tmp/ .claude/program/ .claude/repo/"

    # Telemetry fallback dir: the emitter's isEnabled() checks for it when
    # settings.skailr.json carries no explicit telemetry.enabled. Left empty and
    # gitignored; no placeholder file — .skailr/ is ignored so an empty dir stays invisible.
    New-Item -ItemType Directory -Path "$Target\.skailr" -Force | Out-Null
    Write-Host "  + .skailr/"
}

$PackagedRules = @(
    "engineer", "verifier", "researcher", "program-architect", "intake"
)
$PackagedCommands = @(
    "patch", "build", "program", "map-repo", "yolo", "yolo-program"
)

function Install-Cursor {
    New-Item -ItemType Directory -Path "$Target\.cursor\rules" -Force | Out-Null
    New-Item -ItemType Directory -Path "$Target\.cursor\commands" -Force | Out-Null

    foreach ($name in $PackagedRules) {
        $src = Join-Path $ScriptDir ".cursor\rules\$name.mdc"
        if (Test-Path $src) {
            Copy-Item $src "$Target\.cursor\rules\$name.mdc" -Force
            Write-Host "  + .cursor/rules/$name.mdc"
        }
    }
    foreach ($name in $PackagedCommands) {
        $src = Join-Path $ScriptDir ".cursor\commands\$name.md"
        if (Test-Path $src) {
            Copy-Item $src "$Target\.cursor\commands\$name.md" -Force
            Write-Host "  + .cursor/commands/$name.md"
        }
    }
    $readme = Join-Path $ScriptDir ".cursor\README.md"
    if (Test-Path $readme) {
        Copy-Item $readme "$Target\.cursor\README.md" -Force
        Write-Host "  + .cursor/README.md"
    }

    $intakeTarget = "$Target\.claude\intake.md"
    if (-not (Test-Path $intakeTarget)) {
        $intakeSrc = Join-Path $ScriptDir ".claude\intake.md"
        if (Test-Path $intakeSrc) {
            Copy-Item $intakeSrc $intakeTarget -Force
            Write-Host "  + .claude/intake.md (needed by Cursor intake rule)"
        }
    }
    New-Item -ItemType Directory -Path "$Target\.claude\tmp" -Force | Out-Null
    New-Item -ItemType Directory -Path "$Target\.claude\program" -Force | Out-Null
    New-Item -ItemType Directory -Path "$Target\.claude\repo" -Force | Out-Null
    foreach ($keep in @("$Target\.claude\tmp\.gitkeep", "$Target\.claude\program\.gitkeep", "$Target\.claude\repo\.gitkeep")) {
        if (-not (Test-Path $keep)) { New-Item -ItemType File -Path $keep -Force | Out-Null }
    }
}

# DOC: 3.0 retire phase. skailr-agents ≤2.x shipped an orchestration framework that 3.0
# removed — see docs/DESIGN-3.0.md. On upgrade, those pack-owned files must not linger in
# the target. Only EXACT paths the ≤2.x pack itself shipped are listed; consumer data
# (.claude/experts/, program runtime, .claude/tmp/, the CLAUDE.md conventions zone) is
# never listed and never touched. Keep in sync with install.sh's RETIRED_* arrays.
$RetiredDirs = @(
    ".claude\agents\content", ".claude\agents\design", ".claude\agents\finance",
    ".claude\agents\legal", ".claude\agents\marketing", ".claude\agents\pm",
    ".claude\agents\portfolio", ".claude\agents\experts",
    ".claude\teams", ".claude\program\channels"
)
$RetiredSkills = @(
    "archive-program-state", "check-ownership", "cleanup-scoped-artifacts",
    "compile-status-digest", "consult-or-mint", "curate-expert", "drain-exception-inbox",
    "emit-stubs", "emit-telemetry", "fit-test", "freeze-contract", "reconcile-model",
    "resume-from-feature-progress", "resume-from-ledger", "route-channels", "route-intake",
    "route-models", "run-feature-queue", "run-gated-pipeline", "run-ticket-board",
    "sync-lineage", "trace-requirement", "track-phase", "write-handoff-and-yield"
)
$RetiredFiles = @(
    ".claude\agents\engineering\architect.md",
    ".claude\agents\engineering\backend-engineer.md",
    ".claude\agents\engineering\data-engineer.md",
    ".claude\agents\engineering\e2e-verifier.md",
    ".claude\agents\engineering\frontend-engineer.md",
    ".claude\agents\engineering\story-writer.md",
    ".claude\agents\engineering\validator.md",
    ".claude\agents\program\integration-verifier.md",
    ".claude\agents\program\program-documenter.md",
    ".claude\agents\program\program-validator.md",
    ".claude\commands\ship-feature.md", ".claude\commands\build-feature.md",
    ".claude\commands\continue-feature.md", ".claude\commands\continue-program.md",
    ".claude\commands\discover.md", ".claude\commands\plan-program.md",
    ".claude\commands\build-program.md", ".claude\commands\discover-portfolio.md",
    ".claude\commands\plan-portfolio.md", ".claude\commands\status-portfolio.md",
    ".claude\commands\mint-expert.md",
    ".claude\model-routing.json",
    ".claude\program\schemas\artboard.template.md",
    ".claude\program\schemas\backlog.template.md",
    ".claude\program\schemas\board.template.md",
    ".claude\program\schemas\budget-ledger.template.md",
    ".claude\program\schemas\completion-report.template.md",
    ".claude\program\schemas\contract.template.md",
    ".claude\program\schemas\design-brief.template.md",
    ".claude\program\schemas\dispatch-packet.template.md",
    ".claude\program\schemas\expert-config.schema.json",
    ".claude\program\schemas\expert-profile.template.md",
    ".claude\program\schemas\expert-registry.template.md",
    ".claude\program\schemas\expert-research.template.md",
    ".claude\program\schemas\expert.schema.json",
    ".claude\program\schemas\feature-progress.template.md",
    ".claude\program\schemas\field-guide.template.md",
    ".claude\program\schemas\handoff.template.md",
    ".claude\program\schemas\ledger.template.md",
    ".claude\program\schemas\map-repo-progress.template.md",
    ".claude\program\schemas\map-report.template.md",
    ".claude\program\schemas\patch-report.template.md",
    ".claude\program\schemas\telemetry-event.schema.json",
    ".claude\program\schemas\ticket.template.md",
    ".claude\program\schemas\ui-spec.template.md",
    "scripts\skailr\apply-model-routing.mjs", "scripts\skailr\archive-program.mjs",
    "scripts\skailr\check-agent-tools.mjs", "scripts\skailr\check-blocks.mjs",
    "scripts\skailr\check-contracts.mjs", "scripts\skailr\check-experts.mjs",
    "scripts\skailr\check-phase-tracking.mjs", "scripts\skailr\cleanup-scoped.mjs",
    "scripts\skailr\db.mjs", "scripts\skailr\lib\db.mjs", "scripts\skailr\lib\render.mjs",
    "scripts\skailr\emit-stubs.mjs", "scripts\skailr\emit-telemetry.mjs",
    "scripts\skailr\feature-status.mjs", "scripts\skailr\ledger-status.mjs",
    "scripts\skailr\rotate-channels.mjs", "scripts\skailr\route-prompt.mjs",
    "scripts\skailr\status.mjs", "scripts\skailr\telemetry-smoke.mjs",
    "scripts\skailr\ticket-status.mjs", "scripts\skailr\validate-channels.mjs",
    ".cursor\model-routing.md"
)
$RetiredCursorRules = @(
    "architect", "backend-engineer", "content-editor", "content-lead", "content-strategist",
    "content-writer", "data-engineer", "e2e-verifier", "frontend-engineer", "integration-verifier",
    "program-documenter", "program-validator", "story-writer", "validator", "registry",
    "portfolio-architect", "initiative-lead",
    "legal-lead", "legal-analyst", "compliance-reviewer", "legal-validator",
    "pm-lead", "pm-planner", "risk-analyst", "status-reporter",
    "design-lead", "design-strategist", "designer", "design-reviewer",
    "mkt-lead", "mkt-strategist", "channel-planner", "mkt-analyst",
    "fin-lead", "fin-modeler", "fin-analyst", "fin-auditor",
    "expert", "expert-scout"
)
$RetiredCursorCommands = @(
    "ship-feature", "build-feature", "continue-feature", "discover", "plan-program",
    "build-program", "continue-program", "discover-portfolio", "plan-portfolio",
    "status-portfolio", "mint-expert"
)

function Invoke-RetireLegacy {
    $removed = 0
    foreach ($d in $RetiredDirs) {
        $p = Join-Path $Target $d
        if (Test-Path $p -PathType Container) { Remove-Item $p -Recurse -Force; $removed++ }
    }
    foreach ($s in $RetiredSkills) {
        $p = Join-Path $Target ".claude\skills\$s"
        if (Test-Path $p -PathType Container) { Remove-Item $p -Recurse -Force; $removed++ }
    }
    foreach ($f in $RetiredFiles) {
        $p = Join-Path $Target $f
        if (Test-Path $p -PathType Leaf) { Remove-Item $p -Force; $removed++ }
    }
    foreach ($r in $RetiredCursorRules) {
        $p = Join-Path $Target ".cursor\rules\$r.mdc"
        if (Test-Path $p -PathType Leaf) { Remove-Item $p -Force; $removed++ }
    }
    foreach ($c in $RetiredCursorCommands) {
        $p = Join-Path $Target ".cursor\commands\$c.md"
        if (Test-Path $p -PathType Leaf) { Remove-Item $p -Force; $removed++ }
    }
    $lib = Join-Path $Target "scripts\skailr\lib"
    if ((Test-Path $lib -PathType Container) -and -not (Get-ChildItem $lib)) {
        Remove-Item $lib -Force
    }
    if ($removed -gt 0) {
        Write-Host "  - retired $removed pre-3.0 pack file(s)/dir(s) (see docs/DESIGN-3.0.md)"
    }
}

# Ordered list of migration ids implemented by scripts/skailr/migrate.mjs. All logic lives
# in the runner; this array is only the ordered call list. It is asserted identical to the
# runner's exports and to install.sh's SKAILR_MIGRATIONS by scripts/skailr/doctor.mjs, so
# ids must stay lowercase-hyphen (/^[a-z][a-z0-9-]*$/) and the literal must contain no
# parentheses beyond its own delimiters — doctor's extractor drops anything else.
$SkailrMigrations = @(
    "telemetry-enabled-default",
    "autoupdate-enabled-default"
)

# Additive-only upgrade migrations. Runs AFTER the copy phase (so it sees final on-disk
# state) and BEFORE the gitignore/finish steps. Never fatal: the runner reports and exits 0
# for unparseable/unwritable files, and the try/catch covers even a usage error, because
# $ErrorActionPreference = "Stop" must not abort an install here.
function Invoke-Migrations {
    if ($Mode -eq "cursor") { return }   # .claude/ is not managed in cursor-only mode
    if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
        Write-Host "  ! migrations skipped (node not on PATH; install continues)"
        return
    }
    if ([string]::IsNullOrEmpty($MigratePreExisting)) {
        Write-Host "  = migrations skipped (fresh install; shipped defaults already current)"
        return
    }
    foreach ($id in $SkailrMigrations) {
        # Invoked from $ScriptDir (the pack), never from $Target: the target's copy of the
        # runner may be an older version that predates this migration.
        try {
            & node (Join-Path $ScriptDir "scripts\skailr\migrate.mjs") `
                --target $Target --only $id --pre-existing $MigratePreExisting
        } catch {
            Write-Host "  ! migrations skipped ($_)"
        }
    }
}

# Refresh $Target\.skailr\installed-version.json on EVERY claude-mode install/upgrade — it is
# the "installed" side of the update check and must track the pack, unlike autoUpdate.enabled
# (user-editable, copy-once-if-absent). Runs unconditionally, not gated on $MigratePreExisting:
# a fresh install needs the marker too. Never fatal — the runner always exits 0 and the
# try/catch covers even a usage error, because $ErrorActionPreference = "Stop" must not abort
# an install here.
function Invoke-RecordInstall {
    if ($Mode -eq "cursor") { return }   # .claude/ is not managed in cursor-only mode
    if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
        Write-Host "  ! installed-version marker skipped (node not on PATH; install continues)"
        return
    }
    # Invoked from $ScriptDir (the pack), never from $Target: the version stamped must be the
    # pack's own package.json version, and the target's copy may predate this script entirely.
    try {
        & node (Join-Path $ScriptDir "scripts\skailr\check-update.mjs") `
            --record-install --target $Target
    } catch {
        Write-Host "  ! installed-version marker skipped ($_)"
    }
}

function Append-Gitignore {
    $gi = Join-Path $Target ".gitignore"
    if (-not (Test-Path $gi)) { New-Item -ItemType File -Path $gi -Force | Out-Null }
    $lines = @(
        ".DS_Store",
        ".claude/tmp/*",
        "!.claude/tmp/.gitkeep",
        ".claude/program/*",
        "!.claude/program/.gitkeep",
        "!.claude/program/channels/",
        ".claude/program/channels/*",
        "!.claude/program/channels/PROTOCOL.md",
        "!.claude/program/channels/program.md",
        "!.claude/program/channels/feature.md",
        "!.claude/program/schemas/",
        ".skailr/",
        "node_modules/"
    )
    $existing = @(Get-Content $gi -ErrorAction SilentlyContinue)
    if ($existing -contains ".claude/program/") {
        $existing = $existing | Where-Object { $_ -ne ".claude/program/" }
        Set-Content -Path $gi -Value $existing
        Write-Host "  ~ .gitignore removed obsolete .claude/program/"
    }
    $existing = @(Get-Content $gi -ErrorAction SilentlyContinue)
    foreach ($line in $lines) {
        if ($existing -contains $line) {
            Write-Host "  = .gitignore already has $line"
        } else {
            Add-Content -Path $gi -Value $line
            Write-Host "  + .gitignore ← $line"
        }
    }
}

# Snapshot which migration targets existed BEFORE the copy phase. A file the copy phase
# creates in this same run already carries current shipped defaults, so migrating it would
# be a redundant double-write; only genuinely pre-existing consumer files are candidates.
$MigratePreExisting = if (Test-Path "$Target\.claude\settings.skailr.json") { ".claude/settings.skailr.json" } else { "" }

switch ($Mode) {
    "both" { Install-Claude; Install-Cursor; Install-Scripts }
    "claude" { Install-Claude; Install-Scripts }
    "cursor" { Install-Cursor }
}

Invoke-RetireLegacy
Invoke-Migrations
Invoke-RecordInstall
Append-Gitignore
Write-Host "Done."
