#!/usr/bin/env bash
# Regenerate .cursor/ mirror and manifest.json from authoritative .claude/ tree.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

python3 <<'PY'
import json
from pathlib import Path

ROOT = Path(".").resolve()
CLAUDE_AGENTS = ROOT / ".claude" / "agents"
CLAUDE_CMDS = ROOT / ".claude" / "commands"
CURSOR_RULES = ROOT / ".cursor" / "rules"
CURSOR_CMDS = ROOT / ".cursor" / "commands"
CURSOR_RULES.mkdir(parents=True, exist_ok=True)
CURSOR_CMDS.mkdir(parents=True, exist_ok=True)

WRITE_RESTRICTED = {
    "researcher": "Read, Grep, Glob, Write, Edit — Write/Edit only for the artifact the dispatch names (ask answer, orientation.md, recon note); never edit application code.",
    "verifier": "Read, Grep, Glob, Bash, Write, Edit — Write/Edit solely for verification-report.md; never edit application code, even for a one-line fix.",
}

def parse_frontmatter(text):
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    fm_raw = text[3:end].strip()
    body = text[end + 4:].lstrip("\n")
    fm = {}
    for line in fm_raw.splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            fm[k.strip()] = v.strip()
    return fm, body

agent_files = []
root_md = list(CLAUDE_AGENTS.glob("*.md"))
if root_md:
    raise SystemExit(
        "flat agent files are not allowed under .claude/agents/; "
        f"move into a subdirectory: {[p.name for p in root_md]}"
    )
for d in sorted(p for p in CLAUDE_AGENTS.iterdir() if p.is_dir()):
    agent_files += list(d.glob("*.md"))

for src in sorted(agent_files):
    text = src.read_text()
    fm, body = parse_frontmatter(text)
    name = fm.get("name", src.stem)
    desc = fm.get("description", name)
    tools = fm.get("tools", "")
    model = fm.get("model", "sonnet")
    restriction_note = ""
    if name in WRITE_RESTRICTED:
        restriction_note = (
            f"<!-- Cursor limitation: Claude Code tools are [{tools}]. "
            f"Cursor rules cannot enforce tool allowlists; honor the restriction in prose below. -->\n\n"
            f"**Tool restriction (honor manually):** {WRITE_RESTRICTED[name]}\n\n"
        )
    out = (
        f"---\n"
        f"description: {desc}\n"
        f"alwaysApply: false\n"
        f"---\n\n"
        f"{restriction_note}"
        f"{body}"
    )
    (CURSOR_RULES / f"{name}.mdc").write_text(out)
    print(f"rule: {name}")

intake_src = ROOT / ".claude" / "intake.md"
if not intake_src.exists():
    raise SystemExit("missing .claude/intake.md")
intake_body = intake_src.read_text().lstrip()
# Drop leading H1 if present — rule title follows frontmatter
intake_for_rule = intake_body
intake_mdc = (
    "---\n"
    "description: Skailr plain-chat intake — answer questions directly, small changes to /patch, features to /build, program-scale scope to /program, repo baselining to /map-repo. Always loaded.\n"
    "alwaysApply: true\n"
    "---\n\n"
    f"{intake_for_rule}"
)
(CURSOR_RULES / "intake.mdc").write_text(intake_mdc)
print("rule: intake")

claude_md = (
    "<!-- Generated by scripts/remirror.sh from .claude/intake.md — do not hand-edit; re-run remirror. -->\n\n"
    "<!-- skailr:intake:start -->\n"
    f"{intake_body.rstrip()}\n"
    "<!-- skailr:intake:end -->\n"
)
(ROOT / "CLAUDE.md").write_text(claude_md)
print("CLAUDE.md")

CURSOR_NOTE = """<!--
Cursor execution note: Claude Code dispatches subagents via the Task tool.
Cursor has no native cross-agent Task dispatch. In Cursor, run this orchestration
in one agent session by invoking the corresponding `.cursor/rules/<agent>.mdc`
roles in sequence (or via Background Agents for parallel engineer/workstream steps).
The phase order, gates, and contracts below are unchanged — only the dispatch mechanism differs.
-->

"""

for src in sorted(CLAUDE_CMDS.glob("*.md")):
    text = src.read_text()
    fm, body = parse_frontmatter(text)
    name = src.stem
    desc = fm.get("description", name)
    out = (
        f"---\n"
        f"name: {name}\n"
        f"description: {desc}\n"
        f"---\n\n"
        f"{CURSOR_NOTE}"
        f"{body}"
    )
    (CURSOR_CMDS / f"{name}.md").write_text(out)
    print(f"cmd:  {name}")

# Map agent subdirectory name → manifest tier
DIR_TIER = {
    "engineering": "workstream",
    "program": "program",
}
COMMANDS = {
    "patch": "workstream",
    "build": "workstream",
    "yolo": "workstream",
    "program": "program",
    "yolo-program": "program",
    "map-repo": "program",
}
entries = []
agents_root = ROOT / ".claude" / "agents"
root_md = list(agents_root.glob("*.md"))
if root_md:
    raise SystemExit(
        "flat agent files are not allowed under .claude/agents/; "
        f"move into a subdirectory: {[p.name for p in root_md]}"
    )
for d in sorted(p for p in agents_root.iterdir() if p.is_dir()):
    tier = DIR_TIER.get(d.name, d.name)
    for p in sorted(d.glob("*.md")):
        name = p.stem
        entries.append({
            "id": name, "tier": tier, "type": "agent",
            "claude_path": f".claude/agents/{d.name}/{name}.md",
            "cursor_path": f".cursor/rules/{name}.mdc",
        })
for name, tier in sorted(COMMANDS.items()):
    entries.append({
        "id": name, "tier": tier, "type": "command",
        "claude_path": f".claude/commands/{name}.md",
        "cursor_path": f".cursor/commands/{name}.md",
    })
# skills
skills_root = ROOT / ".claude" / "skills"
if skills_root.exists():
    for skill_dir in sorted(skills_root.iterdir()):
        skill_md = skill_dir / "SKILL.md"
        if skill_md.exists():
            entries.append({
                "id": f"skill-{skill_dir.name}",
                "tier": "skill",
                "type": "skill",
                "claude_path": str(skill_md.relative_to(ROOT)),
                "cursor_path": None,
            })
entries.append({
    "id": "intake",
    "tier": "config",
    "type": "intake",
    "claude_path": ".claude/intake.md",
    "cursor_path": ".cursor/rules/intake.mdc",
})
entries.append({
    "id": "claude-md",
    "tier": "config",
    "type": "config",
    "claude_path": "CLAUDE.md",
    "cursor_path": None,
})
for schema in (
    "ownership.schema.json",
    "ownership.example.json",
    "orientation.template.md",
):
    p = ROOT / ".claude" / "program" / "schemas" / schema
    if not p.exists():
        continue
    entries.append({
        "id": f"schema-{Path(schema).stem}",
        "tier": "program",
        "type": "schema",
        "claude_path": f".claude/program/schemas/{schema}",
        "cursor_path": None,
    })

missing = [e[k] for e in entries for k in ("claude_path", "cursor_path") if e.get(k) and not (ROOT / e[k]).exists()]
if missing:
    raise SystemExit(f"missing paths: {missing}")

manifest = {
    "name": "skailr-agents",
    "description": "Thin layer over Claude Code — main-session-led builds, fresh-context verification, durable CLAUDE.md context",
    "version": json.loads((ROOT / "package.json").read_text())["version"],
    "artifacts": entries,
}
(ROOT / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
print(f"manifest: {len(entries)} artifacts")
PY

echo "Remirror complete."
